// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialHeroes.Infra.Data.Context;

namespace SocialHeroes.Infra.Data.Migrations
{
    [DbContext(typeof(SocialHeroesContext))]
    partial class SocialHeroesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<Guid>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Complement")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("District")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18, 9)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18, 9)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Street")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<Guid>("UserId");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasMaxLength(8);

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.Blood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("Varchar(3)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Bloods");
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.BloodNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Actived");

                    b.Property<int>("AmountBlood");

                    b.Property<Guid>("BloodId");

                    b.Property<Guid>("NotificationId");

                    b.Property<bool>("ShareOnFacebook");

                    b.Property<bool>("ShareOnInstagram");

                    b.Property<bool>("ShareOnTwitter");

                    b.Property<bool>("ShareOnWhatsapp");

                    b.HasKey("Id");

                    b.HasIndex("BloodId");

                    b.HasIndex("NotificationId");

                    b.ToTable("BloodNotifications");
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.BreastMilkNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Actived");

                    b.Property<int>("AmountBreastMilk");

                    b.Property<Guid>("NotificationId");

                    b.Property<bool>("ShareOnFacebook");

                    b.Property<bool>("ShareOnInstagram");

                    b.Property<bool>("ShareOnTwitter");

                    b.Property<bool>("ShareOnWhatsapp");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId")
                        .IsUnique();

                    b.ToTable("BreastMilkNotifications");
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.DonatorUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("ActivedBloodNotification");

                    b.Property<bool>("ActivedBreastMilkNotification");

                    b.Property<bool>("ActivedHairNotification");

                    b.Property<Guid?>("BloodId");

                    b.Property<string>("CPF")
                        .HasColumnType("varchar(11)")
                        .HasMaxLength(11);

                    b.Property<string>("CellPhone")
                        .HasColumnType("varchar(14)")
                        .HasMaxLength(14);

                    b.Property<DateTime>("DateBirth");

                    b.Property<int>("Genre");

                    b.Property<Guid?>("HairId");

                    b.Property<DateTime?>("LastBloodNotification");

                    b.Property<DateTime?>("LastBreastMilkNotification");

                    b.Property<DateTime?>("LastDonatedBlood");

                    b.Property<DateTime?>("LastDonatedBreastMilk");

                    b.Property<DateTime?>("LastDonatedHair");

                    b.Property<DateTime?>("LastHairNotification");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("BloodId");

                    b.HasIndex("HairId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DonatorUsers");
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.DonatorUserBloodNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Appear");

                    b.Property<Guid>("BloodNotificationId");

                    b.Property<DateTime?>("DateAppeared");

                    b.Property<Guid>("DonatorUserId");

                    b.HasKey("Id");

                    b.HasIndex("BloodNotificationId");

                    b.HasIndex("DonatorUserId");

                    b.ToTable("DonatorUserBloodNotifications");
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.DonatorUserBreastMilkNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Appear");

                    b.Property<Guid>("BreastMilkNotificationId");

                    b.Property<DateTime?>("DateAppeared");

                    b.Property<Guid>("DonatorUserId");

                    b.HasKey("Id");

                    b.HasIndex("BreastMilkNotificationId");

                    b.HasIndex("DonatorUserId");

                    b.ToTable("DonatorUserBreastMilkNotifications");
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.DonatorUserHairNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Appear");

                    b.Property<DateTime?>("DateAppeared");

                    b.Property<Guid>("DonatorUserId");

                    b.Property<Guid>("HairNotificationId");

                    b.HasKey("Id");

                    b.HasIndex("DonatorUserId");

                    b.HasIndex("HairNotificationId");

                    b.ToTable("DonatorUserHairNotifications");
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.Hair", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("Varchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("Color", "Type")
                        .IsUnique();

                    b.ToTable("Hairs");
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.HairNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Actived");

                    b.Property<int>("AmountHair");

                    b.Property<Guid>("HairId");

                    b.Property<Guid>("NotificationId");

                    b.Property<bool>("ShareOnFacebook");

                    b.Property<bool>("ShareOnInstagram");

                    b.Property<bool>("ShareOnTwitter");

                    b.Property<bool>("ShareOnWhatsapp");

                    b.HasKey("Id");

                    b.HasIndex("HairId");

                    b.HasIndex("NotificationId");

                    b.ToTable("HairNotifications");
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.InstitutionUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("varchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("FantasyName")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<Guid?>("NotificationId");

                    b.Property<string>("SocialReason")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("InstitutionUsers");
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateNotification");

                    b.Property<Guid>("InstitutionUserId");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.NotificationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("NotificationTypes");
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.Phone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("InstitutionUserId");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.HasIndex("InstitutionUserId");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128);

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<int>("UserStatus");

                    b.Property<int>("UserType");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.UserNotificationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("NotificationTypeId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("NotificationTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserNotificationTypes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("SocialHeroes.Domain.Models.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SocialHeroes.Domain.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SocialHeroes.Domain.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("SocialHeroes.Domain.Models.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SocialHeroes.Domain.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SocialHeroes.Domain.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.Address", b =>
                {
                    b.HasOne("SocialHeroes.Domain.Models.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("SocialHeroes.Domain.Models.Address", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.BloodNotification", b =>
                {
                    b.HasOne("SocialHeroes.Domain.Models.Blood", "Blood")
                        .WithMany("BloodNotifications")
                        .HasForeignKey("BloodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SocialHeroes.Domain.Models.Notification", "Notification")
                        .WithMany("BloodNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.BreastMilkNotification", b =>
                {
                    b.HasOne("SocialHeroes.Domain.Models.Notification", "Notification")
                        .WithOne("BreastMilkNotification")
                        .HasForeignKey("SocialHeroes.Domain.Models.BreastMilkNotification", "NotificationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.DonatorUser", b =>
                {
                    b.HasOne("SocialHeroes.Domain.Models.Blood", "Blood")
                        .WithMany("DonatorsUsers")
                        .HasForeignKey("BloodId");

                    b.HasOne("SocialHeroes.Domain.Models.Hair", "Hair")
                        .WithMany("DonatorsUsers")
                        .HasForeignKey("HairId");

                    b.HasOne("SocialHeroes.Domain.Models.User", "User")
                        .WithOne("DonatorUser")
                        .HasForeignKey("SocialHeroes.Domain.Models.DonatorUser", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.DonatorUserBloodNotification", b =>
                {
                    b.HasOne("SocialHeroes.Domain.Models.BloodNotification", "BloodNotification")
                        .WithMany("DonatorUserBloodNotifications")
                        .HasForeignKey("BloodNotificationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SocialHeroes.Domain.Models.DonatorUser", "DonatorUser")
                        .WithMany("DonatorUserBloodNotifications")
                        .HasForeignKey("DonatorUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.DonatorUserBreastMilkNotification", b =>
                {
                    b.HasOne("SocialHeroes.Domain.Models.BreastMilkNotification", "BreastMilkNotification")
                        .WithMany("DonatorUserBreastMilkNotifications")
                        .HasForeignKey("BreastMilkNotificationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SocialHeroes.Domain.Models.DonatorUser", "DonatorUser")
                        .WithMany("DonatorUserBreastMilkNotifications")
                        .HasForeignKey("DonatorUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.DonatorUserHairNotification", b =>
                {
                    b.HasOne("SocialHeroes.Domain.Models.DonatorUser", "DonatorUser")
                        .WithMany("DonatorUserHairNotifications")
                        .HasForeignKey("DonatorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SocialHeroes.Domain.Models.HairNotification", "HairNotification")
                        .WithMany("DonatorUserHairNotifications")
                        .HasForeignKey("HairNotificationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.HairNotification", b =>
                {
                    b.HasOne("SocialHeroes.Domain.Models.Hair", "Hair")
                        .WithMany("HairNotifications")
                        .HasForeignKey("HairId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SocialHeroes.Domain.Models.Notification", "Notification")
                        .WithMany("HairNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.InstitutionUser", b =>
                {
                    b.HasOne("SocialHeroes.Domain.Models.Notification", "Notification")
                        .WithMany("InstitutionUsers")
                        .HasForeignKey("NotificationId");

                    b.HasOne("SocialHeroes.Domain.Models.User", "User")
                        .WithOne("InstitutionUser")
                        .HasForeignKey("SocialHeroes.Domain.Models.InstitutionUser", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.Phone", b =>
                {
                    b.HasOne("SocialHeroes.Domain.Models.InstitutionUser", "InstitutionUser")
                        .WithMany("Phones")
                        .HasForeignKey("InstitutionUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SocialHeroes.Domain.Models.UserNotificationType", b =>
                {
                    b.HasOne("SocialHeroes.Domain.Models.NotificationType", "NotificationType")
                        .WithMany("UserNotificationTypes")
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SocialHeroes.Domain.Models.User", "User")
                        .WithMany("UserNotificationTypes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
